/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.concessionaria.view;

import com.mycompany.concessionaria.model.Veiculo;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Year;
import java.time.format.DateTimeFormatter;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class CadastroVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroVeiculo
     */
    public CadastroVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_VeiculoMarca = new javax.swing.JTextField();
        jTextField_VeiculoModelo = new javax.swing.JTextField();
        jTextField_VeiculoAnoFabricacao = new javax.swing.JTextField();
        jTextFieldVeiculoKm = new javax.swing.JTextField();
        jTextField_VeiculoValor = new javax.swing.JTextField();
        jTextField_VeiculoChassi = new javax.swing.JTextField();
        jButtonVeiculoCancelar = new javax.swing.JButton();
        jButtonVeiculoSalvar = new javax.swing.JButton();
        jRadioButtonVeiculoDisponibilidadeSim = new javax.swing.JRadioButton();
        jRadioButtonVeiculoDisponibilidadeNao = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Veiculos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEquipamentosDeSerie = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEquipamentosOpcionais = new javax.swing.JTable();
        jButton_VeiculoConsultar = new javax.swing.JButton();
        jButton_VeiculoExcluir = new javax.swing.JButton();

        label1.setText("label1");

        setTitle("Cadastro Veículos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Veículos");

        jLabel2.setText("Marca: ");

        jLabel3.setText("Modelo: ");

        jLabel4.setText("Ano Fabricação: ");

        jLabel5.setText("Kilometragem: ");

        jLabel6.setText("Valor: ");

        jLabel7.setText("Chassi: ");

        jLabel8.setText("Disponível: ");

        jButtonVeiculoCancelar.setText("Cancelar");
        jButtonVeiculoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeiculoCancelarActionPerformed(evt);
            }
        });

        jButtonVeiculoSalvar.setText("Salvar");
        jButtonVeiculoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeiculoSalvarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonVeiculoDisponibilidadeSim);
        jRadioButtonVeiculoDisponibilidadeSim.setText("Sim");

        buttonGroup1.add(jRadioButtonVeiculoDisponibilidadeNao);
        jRadioButtonVeiculoDisponibilidadeNao.setText("Não");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Veiculos"));

        jTable_Veiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Marca", "Modelo", "Ano Fab.", "Km", "Valor", "Chassi", "Disponivel"
            }
        ));
        jScrollPane3.setViewportView(jTable_Veiculos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamentos de Série"));

        jTableEquipamentosDeSerie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Nome", "Descrição", "null", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableEquipamentosDeSerie);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamentos Opcionais"));

        jTableEquipamentosOpcionais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Nome", "Descrição", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableEquipamentosOpcionais);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_VeiculoConsultar.setText("Consultar");
        jButton_VeiculoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VeiculoConsultarActionPerformed(evt);
            }
        });

        jButton_VeiculoExcluir.setText("Excluir");
        jButton_VeiculoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VeiculoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_VeiculoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_VeiculoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_VeiculoAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_VeiculoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_VeiculoChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldVeiculoKm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jRadioButtonVeiculoDisponibilidadeSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonVeiculoDisponibilidadeNao))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jButtonVeiculoCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_VeiculoConsultar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_VeiculoExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonVeiculoSalvar))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_VeiculoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_VeiculoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_VeiculoAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldVeiculoKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jRadioButtonVeiculoDisponibilidadeNao)
                            .addComponent(jRadioButtonVeiculoDisponibilidadeSim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_VeiculoChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_VeiculoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVeiculoCancelar)
                    .addComponent(jButton_VeiculoConsultar)
                    .addComponent(jButton_VeiculoExcluir)
                    .addComponent(jButtonVeiculoSalvar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVeiculoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeiculoSalvarActionPerformed
        String marca = jTextField_VeiculoMarca.getText();
        String modelo = jTextField_VeiculoModelo.getText();

        String anoFabricacaoString = jTextField_VeiculoAnoFabricacao.getText();
        DateTimeFormatter formatoAnoVeiculo = DateTimeFormatter.ofPattern("yyyy");
        Year anoFabricacaoVeiculo=null;
        try {
            anoFabricacaoVeiculo = Year.parse(anoFabricacaoString,formatoAnoVeiculo);
        } catch (DateTimeException e){
            JOptionPane.showMessageDialog(rootPane, "Ano Inválida: " + anoFabricacaoString);
        }

        int km = Integer.parseInt(jTextFieldVeiculoKm.getText());

        String precoString = jTextField_VeiculoValor.getText();
        BigDecimal preco=null;
        try {
            String texto = precoString.replace(",",".");
            preco = new BigDecimal(texto);

        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Valor do veículo inválido"+precoString);
        }

        String chassi = jTextField_VeiculoChassi.getText();
        String disponibilidadeSelecionada="";
        for(Enumeration<AbstractButton> botoes = buttonGroup1.getElements(); botoes.hasMoreElements();){
            AbstractButton botao = botoes.nextElement();
            if(botao.isSelected()){
                disponibilidadeSelecionada=botao.getText();
                break;
            }
        }
        boolean disponivel = Boolean.parseBoolean(disponibilidadeSelecionada);

        Veiculo veiculo = new Veiculo(marca, modelo, anoFabricacaoVeiculo, km, preco, chassi, disponivel);

        Path path = Path.of("C:\\Users\\Usuario\\OneDrive\\Documentos\\PJP\\PJP\\Aula6Exercicios\\aula6ExerExtra\\Concessionaria\\veiculo.txt");

        try {

            if (Files.notExists(path)){
                Files.createFile(path);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Houve algum problema para criar o arquivo.");
        }
        try {
            Files.writeString(path, marca + "," + modelo + "," + anoFabricacaoVeiculo + "," + km + "," + precoString + "," + chassi + "," + disponibilidadeSelecionada + "\n",StandardOpenOption.APPEND);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu algum problema para gravar os dados.");
        }

        jTextField_VeiculoMarca.setText("");
        jTextField_VeiculoModelo.setText("");
        jTextFieldVeiculoKm.setText("");
        jTextField_VeiculoAnoFabricacao.setText("");
        jTextField_VeiculoChassi.setText("");
        jTextField_VeiculoValor.setText("");
        jRadioButtonVeiculoDisponibilidadeNao.setSelected(false);
        jRadioButtonVeiculoDisponibilidadeSim.setSelected(false);

        DefaultTableModel dtmTabelaCadastroVeiculo = (DefaultTableModel) jTable_Veiculos.getModel();
        Object [] dadosTabelaVeiculo = {marca,modelo,anoFabricacaoVeiculo,km,preco,chassi,disponibilidadeSelecionada};
        dtmTabelaCadastroVeiculo.addRow(dadosTabelaVeiculo);
    }//GEN-LAST:event_jButtonVeiculoSalvarActionPerformed

    private void jButtonVeiculoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeiculoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVeiculoCancelarActionPerformed

    private void jButton_VeiculoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeiculoConsultarActionPerformed
        Path path = Path.of("veiculo.txt");

        try {
            List<String> linhas = Files.readAllLines(path);
            DefaultTableModel dtmTabelaCadastroVeiculo = (DefaultTableModel) jTable_Veiculos.getModel();
            for (String linha : linhas) {
                String[] dados = linha.split(",");

                if (dados.length >= 6) {
                    String marca = dados[0];
                    String modelo = dados[1];
                    String ano = dados[2];
                    String km = dados[3];
                    String chassi = dados[4];
                    String disponivel = dados[5];
                    String valor = dados[6];
                    
                    Object [] dadosTabelaVeiculo = {marca,modelo,ano,km,chassi,disponivel,valor};
                    dtmTabelaCadastroVeiculo.addRow(dadosTabelaVeiculo);
                    
                } else {
                    System.out.println("Linha com dados incompletos: " + linha);
                }
            }
        } catch (IOException e) {
            System.out.println("Erro ao ler o arquivo: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_VeiculoConsultarActionPerformed

    private void jButton_VeiculoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeiculoExcluirActionPerformed
        if (jTable_Veiculos.getSelectedRow() != -1){
            DefaultTableModel dtmTabelaCadastroVeiculo = (DefaultTableModel) jTable_Veiculos.getModel();
            dtmTabelaCadastroVeiculo.removeRow(jTable_Veiculos.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Para exclusão é necessário selecinoar um registro!");
        }
    }//GEN-LAST:event_jButton_VeiculoExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonVeiculoCancelar;
    private javax.swing.JButton jButtonVeiculoSalvar;
    private javax.swing.JButton jButton_VeiculoConsultar;
    private javax.swing.JButton jButton_VeiculoExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonVeiculoDisponibilidadeNao;
    private javax.swing.JRadioButton jRadioButtonVeiculoDisponibilidadeSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableEquipamentosDeSerie;
    private javax.swing.JTable jTableEquipamentosOpcionais;
    private javax.swing.JTable jTable_Veiculos;
    private javax.swing.JTextField jTextFieldVeiculoKm;
    private javax.swing.JTextField jTextField_VeiculoAnoFabricacao;
    private javax.swing.JTextField jTextField_VeiculoChassi;
    private javax.swing.JTextField jTextField_VeiculoMarca;
    private javax.swing.JTextField jTextField_VeiculoModelo;
    private javax.swing.JTextField jTextField_VeiculoValor;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
